version: '3.5'

x-volumes:
  &keys-volume
  type: bind
  target: /concourse-keys
  read_only: true

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

networks:
  concourse:
    name: concourse

volumes:
  dbdata:

services:
  concourse-db:
    container_name: concourse-db
    image: postgres:${POSTGRES_CONTAINER_VERSION}
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database
    networks:
      - concourse
    volumes:
      - dbdata:/database
    logging: *default-logging

  concourse-web:
    container_name: concourse-web
    image: concourse/concourse:${CONCOURSE_VERSION}
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: 
      - <<: *keys-volume
        source: ./keys/web
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    networks:
      - concourse
    logging: *default-logging

  concourse-worker:
    container_name: concourse-worker
    image: concourse/concourse:${CONCOURSE_VERSION}
    command: worker
    privileged: true
    depends_on: [concourse-web]
    volumes: 
      - <<: *keys-volume
        source: ./keys/worker
    links: [concourse-web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
    networks:
      - concourse
    logging: *default-logging