#!/usr/bin/env bash

set -e -u
set -o errexit
set -o pipefail
set -o nounset

dtags () {
    local image="${1}"

    wget -q https://registry.hub.docker.com/v1/repositories/"${image}"/tags -O - \
        | tr -d '[]" ' | tr '}' '\n' | awk -F: '{print $3}'
}

dtags "${1}"
