#!/usr/bin/env bash

set -e -u
set -o errexit
set -o pipefail
set -o nounset

# Get Environment Variables
read -ra args < <(< ../.env sed -e /^$/d -e /^#/d | xargs)
export "${args[@]}"

generateKeys() {
  local keys=(
    'session_signing_key rsa web'
    'tsa_host_key ssh web'
    'worker_key ssh worker'
  )
  for key in "${keys[@]}"
  do
    IFS=' ' read -r -a keyDetails <<< "$key"
    generateKey "${keyDetails[@]}"
  done
}

generateKey() {
  docker run --rm -v "$PWD"/"$3":/keys concourse/concourse:"$CONCOURSE_VERSION" \
    generate-key -t "$2" -f /keys/"$1"
} &> /dev/null

echo '🔐   Generating Concourse keys'
pushd "$(dirname "$0")" &> /dev/null

generateKeys
cp ./worker/worker_key.pub ./web/authorized_worker_keys
cp ./web/tsa_host_key.pub ./worker

echo '🔐   Generated Concourse keys'